apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tags
  template:
    metadata:
      labels:
        app: tags
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
